/* Simulation code for InvertedPendulum generated by the OpenModelica Compiler OpenModelica 1.13.2. */
#if !defined(InvertedPendulum__MODEL_H)
#define InvertedPendulum__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "InvertedPendulum_functions.h"


extern void InvertedPendulum_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
extern void InvertedPendulum_initialLinearSystem(int nLinearSystems, LINEAR_SYSTEM_DATA *data);
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void InvertedPendulum_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int InvertedPendulum_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int InvertedPendulum_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int InvertedPendulum_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int InvertedPendulum_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int InvertedPendulum_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int InvertedPendulum_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int InvertedPendulum_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int InvertedPendulum_checkForAsserts(DATA *data, threadData_t *threadData);
extern int InvertedPendulum_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int InvertedPendulum_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int InvertedPendulum_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* InvertedPendulum_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* InvertedPendulum_relationDescription(int i);
extern void InvertedPendulum_function_initSample(DATA *data, threadData_t *threadData);
extern int InvertedPendulum_initialAnalyticJacobianG(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int InvertedPendulum_initialAnalyticJacobianA(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int InvertedPendulum_initialAnalyticJacobianB(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int InvertedPendulum_initialAnalyticJacobianC(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int InvertedPendulum_initialAnalyticJacobianD(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int InvertedPendulum_functionJacG_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int InvertedPendulum_functionJacA_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int InvertedPendulum_functionJacB_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int InvertedPendulum_functionJacC_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int InvertedPendulum_functionJacD_column(void* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* InvertedPendulum_linear_model_frame(void);
extern const char* InvertedPendulum_linear_model_datarecovery_frame(void);
extern int InvertedPendulum_mayer(DATA* data, modelica_real** res, short *);
extern int InvertedPendulum_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int InvertedPendulum_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int InvertedPendulum_setInputData(DATA *data, const modelica_boolean file);
extern int InvertedPendulum_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void InvertedPendulum_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void InvertedPendulum_function_updateSynchronous(DATA * data, threadData_t *threadData, long i);
extern int InvertedPendulum_function_equationsSynchronous(DATA * data, threadData_t *threadData, long i);
extern void InvertedPendulum_read_input_fmu(MODEL_DATA* modelData, SIMULATION_INFO* simulationData);
extern void InvertedPendulum_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int InvertedPendulum_inputNames(DATA* data, char ** names);
extern int InvertedPendulum_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int InvertedPendulum_functionLocalKnownVars(DATA*, threadData_t*);
extern int InvertedPendulum_symbolicInlineSystem(DATA*, threadData_t*);

#include "InvertedPendulum_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(InvertedPendulum__MODEL_H) */


